name: Manual CI/CD for .NET App

on:
  workflow_dispatch:
    branches:
      - master  # ✅ Only allow running from master branch

jobs:
  build-and-deploy:
    name: Build and Deploy (.NET Framework 4.5.2)
    runs-on: windows-latest

    steps:
      - name: ⏬ Checkout Code
        uses: actions/checkout@v4

      - name: 🏗️ Build Application using MSBuild
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" "ApnaBank/ApnaBank.sln" /p:Configuration=Release /p:SignAssembly=false /p:GenerateClickOnceManifests=false

      - name: ✅ Done
        run: echo "CI workflow completed successfully."
